GET http://localhost:3020/
Content-Type: application/json

###

POST http://localhost:3020/pokemons
Content-Type: application/json

{   
    "dex": 1,
    "name": "bulbasaurssss",
    "type": ["Poison", "Grass"],
    "weaknesses": {
        "Normal": 1,
        "Fire": 2,
        "Water": 0.5,
        "Eletric": 0.5,
        "Grass": 0.25,
        "Ice": 2,
        "Fight": 0.5,
        "Poison": 1,
        "Ground": 1,
        "Flying": 2,
        "Psychc": 2,
        "Bug": 1,
        "Rock": 1,
        "Ghost": 1,
        "Dragon": 1,
        "Dark": 1,
        "Steel": 1,
        "Fairy": 0.5},
    "active": true,
    "evolution": ["ivysaur", "venosaur"],
    "sprite": { "back": "https://img.pokemondb.net/sprites/black-white/anim/back-normal/bulbasaur.gif",
                "front": "https://img.pokemondb.net/sprites/black-white/anim/normal/bulbasaur.gif" 
                },
    "expGrowth": 1059862,
    "moves": ["Tackle", "Growl", "Vine Whip"],
    "baseExperience": 64,
    "captureRate": 45,
    "generation": 1,
    "genderRatio": {
    "male": 87.5,
    "female": 12.5
    },
    "eggGroups": ["Monster", "Grass"],
    "baseFriendship": 70,
    "habitat": "Grassland"
    
}

###
// buscar todos os pokemons
GET http://localhost:3020/pokemons
Content-Type: application/json

###
// buscar pelo id do pokemon
GET http://localhost:3020/pokemons/64dadc58d74f36f11338c6f9
Content-Type: application/json

###
// editar o pokemon
PUT http://localhost:3020/pokemons/64de7225247d15c4b873ad61
Content-Type: application/json

{   
    "dex": 1,
    "name": "bulbasaur",
    "type": ["Poison", "Grass"],
    "weaknesses": {
        "Normal": 2,
        "Fire": 2,
        "Water": 0.5,
        "Eletric": 0.5,
        "Grass": 0.25,
        "Ice": 2,
        "Fight": 0.5,
        "Poison": 1,
        "Ground": 1,
        "Flying": 2,
        "Psychc": 2,
        "Bug": 1,
        "Rock": 1,
        "Ghost": 1,
        "Dragon": 1,
        "Dark": 1,
        "Steel": 1,
        "Fairy": 0.5},
    "active": true,
    "evolution": ["ivysaur", "venosaur"],
    "sprite": { "back": "https://img.pokemondb.net/sprites/black-white/anim/back-normal/bulbasaur.gif",
                "front": "https://img.pokemondb.net/sprites/black-white/anim/normal/bulbasaur.gif" 
                },
    "expGrowth": 1059862,
    "moves": ["Tackle", "Growl", "Vine Whip"]
}

###
//deletar o pokemon

DELETE http://localhost:3020/pokemons/64dea085aa4cf115886cf7f6
Content-Type: application/json

###

PATCH http://localhost:3020/pokemons/64dadcaad74f36f11338c6fb
Content-Type: application/json

{
    "active": true
}

###
// get com query
GET http://localhost:3020/pokemons?type=2
Content-Type: application/json


################################
//trainer
################################

###

GET http://localhost:3020/trainer
Content-Type: application/json

###

POST http://localhost:3020/trainer
Content-Type: application/json

{
    "name": "matheus",
    "gender": "male",
    "region": "kanto",
    "badge": ["boulder"],
    "pokemons": ["bulbasaur"]
}

###
// buscar todos os treinadores
GET http://localhost:3020/trainer
Content-Type: application/json

###
// buscar pelo id do treinador
GET http://localhost:3020/trainer/64dfc3acb70c3f098c2b5638
Content-Type: application/json

###
// editar o treinador
PUT http://localhost:3020/trainer/64dfc3acb70c3f098c2b5638
Content-Type: application/json

{
    "name": "matheus",
    "gender": "male",
    "region": "kanto",
    "badge": ["boulder"],
    "pokemons": ["bulbasaur"]
}

###
//deletar o treinador

DELETE http://localhost:3020/trainer/64dfc3acb70c3f098c2b5638
Content-Type: application/json

###
PATCH http://localhost:3020/trainer/64dfdaf5a52127e89c23e8b7
Content-Type: application/json

{
    "gender": "male"
}

###
// get com query
GET http://localhost:3020/trainer?gender=female
Content-Type: application/json

################################
//myPokemons
################################
// criar o meu pokemon
POST http://localhost:3020/my-pokemons
Content-Type: application/json

{
    "pokemon": "bulbasaur",
    "height": 0.7,
    "weight": 6.9,
    "abilities": ["Overgrow"],
    "gender": "male",
    "evolution": {
    "evolvesFrom": null,
    "evolvesTo": {
      "name": "Ivysaur",
      "method": "Level up",
      "trigger": null,
      "level": 16
    }
    },
    "description": "A strange seed was planted on its back at birth...",
    "stats": {
        "HP": 100,
        "Attack": 100,
        "Defense": 100,
        "Sp_Attack": 100,
        "Sp_Defense": 100,
        "Speed": 100
    },
    "shiny": true,
    "level":12,
    "exp":122
    
}

###
// buscar todos os meus pokemons
GET http://localhost:3020/my-pokemons
Content-Type: application/json

###
// buscar pelo id do meu pokemon
GET http://localhost:3020/my-pokemons/64e0323b5191d99d4a135e01
Content-Type: application/json


###
// editar o meu pokemon
PUT http://localhost:3020/my-pokemons/64e0323b5191d99d4a135e01
Content-Type: application/json

{
    "pokemon": "bulbasaurr",
    "height": 0.7,
    "weight": 6.9,
    "abilities": ["Overgrow"],
    "gender": "male",
    "evolution": {
    "evolvesFrom": null,
    "evolvesTo": {
      "_id": "id_do_pokemon_evoluido"
    }
    },
    "description": "A strange seed was planted on its back at birth...",
    "stats": {
        "HP": 100,
        "Attack": 100,
        "Defense": 100,
        "Sp_Attack": 100,
        "Sp_Defense": 100,
        "Speed": 100
    },
    "shiny": true,
    "level":12,
    "exp":122
    
}

###
//deletar o meu pokemon
DELETE http://localhost:3020/my-pokemons/64e03cfa1cd03f0ab2b39cce
Content-Type: application/json

###
PATCH http://localhost:3020/my-pokemons/64e0323b5191d99d4a135e01
Content-Type: application/json

{
    "gender": "male"
}

###
// get com query
GET http://localhost:3020/my-pokemons?gender=male
Content-Type: application/json

################################
//moves
################################

POST http://localhost:3020/moves
Content-Type: application/json

{
    "number": 1,
    "name": "Tackle",
    "type": "Normal",
    "category": "Physical",
    "damage": 40,
    "accuracy": 100,
    "pp": 35,
    "effect": 0,
    "description": "A physical attack in which the user charges and slams into the target with its whole body.",
    "isHM": false
}

###
// buscar todos os moves
GET http://localhost:3020/moves
Content-Type: application/json

###
// buscar pelo id do move
GET http://localhost:3020/moves/64e7e338b72129b0f0e7a082
Content-Type: application/json

###
// editar o move
PUT http://localhost:3020/moves/64e7e338b72129b0f0e7a082
Content-Type: application/json

{
    "number": 1,
    "name": "Tackle",
    "type": "Normal",
    "category": "Physical",
    "damage": 45,
    "accuracy": 100,
    "pp": 35,
    "effect": 0,
    "description": "A physical attack in which the user charges and slams into the target with its whole body.",
    "isHM": false
}

###
//deletar o move
DELETE http://localhost:3020/moves/64e7e338b72129b0f0e7a082
Content-Type: application/json

###
PATCH http://localhost:3020/moves/64e7e41b16ea7949f568419b
Content-Type: application/json

{
    "type": "fire"
}

###
// get com query
GET http://localhost:3020/moves?type=fire
Content-Type: application/json

################################